name: first workflow

env:
    WORKFLOW_VAR: "This variable is at the workflow level"

on:
  workflow_dispatch:

jobs:

  firstjob:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}

    steps:

      - name: firstJob script
        shell: bash
        run: |
          echo "Hello World! This is the first job for commit: ${VERSION}"

      - name: checkout
        uses: actions/checkout@v4

      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Me"

      - name: time
        run: |
          echo "the time of the greeting was at: ${{ steps.greetings.outputs.time }}"
  




  secondjob:
    needs: firstjob
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      JOB_VAR: "This is a job variable"

    steps:

      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script

      - name: environment variables
        env:
          STEP_VAR: "This is a variable declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "This is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
          echo "The following are default environment variables:"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
